
default: &default
  adapter: mysql2
  database: portfolio
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  encoding: utf8

development:
  adapter: mysql2
  database: portfolio
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  encoding: utf8

production:
  adapter: mysql2
  database: portfolio_pr
  username: portfolio_pr
  password: <%= ENV['DATABASE_PASSWORD'] %>
  encoding: utf8
  pool: 25
  timeout: 5000
